### ISSUE TITLE
Authorization Failure page is broken

### ISSUE THREAD

**Issue by mmoayyed** [doodelicious/cas#35]
Pull the latest from unicon/cas and branch mgmt-webapp. 

Try to access the webapp, but login this time as admin/admin. See the page renders as blank.

See the following stacktrace:

```
2015-07-19 21:37:16,950 DEBUG [org.springframework.web.servlet.DispatcherServlet] - <Could not complete request
org.apache.jasper.JasperException: /WEB-INF/view/jsp/authorizationFailure.jsp (line: 21, column: 1) File [includes/top.jsp] not found
	at org.apache.jasper.compiler.DefaultErrorHandler.jspError(DefaultErrorHandler.java:41)
	at org.apache.jasper.compiler.ErrorDispatcher.dispatch(ErrorDispatcher.java:275)
	at org.apache.jasper.compiler.ErrorDispatcher.jspError(ErrorDispatcher.java:91)
	at org.apache.jasper.compiler.Parser.processIncludeDirective(Parser.java:323)
	at org.apache.jasper.compiler.Parser.parseIncludeDirective(Parser.java:358)
	at org.apache.jasper.compiler.Parser.parseXMLDirective(Parser.java:527)
	at org.apache.jasper.compiler.Parser.parseFileDirectives(Parser.java:1784)
	at org.apache.jasper.compiler.Parser.parse(Parser.java:136)
	at org.apache.jasper.compiler.ParserController.doParse(ParserController.java:227)
	at org.apache.jasper.compiler.ParserController.parseDirectives(ParserController.java:117)
	at org.apache.jasper.compiler.Compiler.generateJava(Compiler.java:194)
	at org.apache.jasper.compiler.Compiler.compile(Compiler.java:356)
	at org.apache.jasper.compiler.Compiler.compile(Compiler.java:336)
	at org.apache.jasper.compiler.Compiler.compile(Compiler.java:323)
	at org.apache.jasper.JspCompilationContext.compile(JspCompilationContext.java:585)
	at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:363)
	at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:396)
	at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:340)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:291)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at org.apache.logging.log4j.web.Log4jServletFilter.doFilter(Log4jServletFilter.java:64)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:721)
	at org.apache.catalina.core.ApplicationDispatcher.processRequest(ApplicationDispatcher.java:466)
	at org.apache.catalina.core.ApplicationDispatcher.doForward(ApplicationDispatcher.java:391)
	at org.apache.catalina.core.ApplicationDispatcher.forward(ApplicationDispatcher.java:318)
	at org.springframework.web.servlet.view.InternalResourceView.renderMergedOutputModel(InternalResourceView.java:168)
	at org.springframework.web.servlet.view.AbstractView.render(AbstractView.java:303)
	at org.springframework.web.servlet.DispatcherServlet.render(DispatcherServlet.java:1244)
	at org.springframework.web.servlet.DispatcherServlet.processDispatchResult(DispatcherServlet.java:1027)
```

**Comment by mmoayyed** [comment]
The page that needs modification is the authorization.jsp file.
