### ISSUE TITLE
Authentication Failiure page crashes with missing JSP

### ISSUE THREAD

**Issue by mmoayyed** [doodelicious/cas#44]
See the error message below please. You may not see this because certain log levels need to be adjusted to DEBUG. Right now, the page simply turns into blank if I log in with admin/admin.

```
2015-07-24 22:12:36,625 DEBUG [org.springframework.web.servlet.DispatcherServlet] - <Could not complete request
org.apache.jasper.JasperException: /WEB-INF/view/jsp/authorizationFailure.jsp (line: 21, column: 1) File [includes/header.nooauth.jsp] not found
        at org.apache.jasper.compiler.DefaultErrorHandler.jspError(DefaultErrorHandler.java:41)
        at org.apache.jasper.compiler.ErrorDispatcher.dispatch(ErrorDispatcher.java:275)
        at org.apache.jasper.compiler.ErrorDispatcher.jspError(ErrorDispatcher.java:91)
        at org.apache.jasper.compiler.Parser.processIncludeDirective(Parser.java:323)
        at org.apache.jasper.compiler.Parser.parseIncludeDirective(Parser.java:358)
        at org.apache.jasper.compiler.Parser.parseDirective(Parser.java:461)
        at org.apache.jasper.compiler.Parser.parseFileDirectives(Parser.java:1782)
        at org.apache.jasper.compiler.Parser.parse(Parser.java:136)
        at org.apache.jasper.compiler.ParserController.doParse(ParserController.java:227)
```

**Comment by mmoayyed** [comment]
In order to actually see the error, find the log4j2.xml file in the web-inf/classes directory and set the org.springframework.web logger level to debug. Restart tomcat.

**Comment by darkape** [comment]
Ah, looks like a typo - it should be header.noauth.jsp, but there is an extra O.
