### ISSUE TITLE
Deleting service does not always show a response

### ISSUE THREAD

**Issue by mmoayyed** [doodelicious/cas#47]
Attempt to delete a service from the dashboard that cannot be deleted, such as the default management app entry. 

The server rejects it:

```
POST http://localhost:8080/cas-management/deleteRegisteredService.html HTTP/1.1
Host: localhost:8080
User-Agent: Mozilla/5.0 (Windows NT 6.3; WOW64; rv:39.0) Gecko/20100101 Firefox/39.0
Accept: */*
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate
Content-Type: application/x-www-form-urlencoded; charset=UTF-8
X-CSRF-TOKEN: f7aac3d6-9c3f-4ded-bfca-7a08786d8984
X-Requested-With: XMLHttpRequest
Referer: http://localhost:8080/cas-management/manage.html
Content-Length: 17
Cookie: JSESSIONID=36BAD07669C1E3FF64176F8A7157B6F9

HTTP/?.? 400 Bad Request
Server: Apache-Coyote/1.1
Cache-Control: no-cache, no-store, max-age=0, must-revalidate
Pragma: no-cache
Expires: 0
X-XSS-Protection: 1; mode=block
X-Frame-Options: DENY
x-content-type-options: nosniff
Content-Type: application/json;charset=UTF-8
Transfer-Encoding: chunked
Date: Wed, 29 Jul 2015 21:28:30 GMT
Connection: close
```

Tomcat logs:

```
java.lang.IllegalArgumentException: The default service http://localhost:8080/cas-management/login/cas cannot be deleted. The definition is required for accessing the application.
	at org.jasig.cas.services.web.ManageRegisteredServicesMultiActionController.deleteRegisteredService(ManageRegisteredServicesMultiActionController.java:139)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
```

The message does not show up on the screen.

**Comment by darkape** [comment]
The alert field is being populated with the error, it just is not being displayed for some reason. :/
