### ISSUE TITLE
Attempting to view errors.jsp causes crash

### ISSUE THREAD

**Issue by mmoayyed** [doodelicious/cas#58]
```
2015-07-31 23:56:25,455 DEBUG [org.springframework.web.servlet.DispatcherServlet] - <Could not complete request
org.apache.jasper.JasperException: /WEB-INF/view/jsp/errors.jsp (line: 21, column: 1) File [includes/header.nooauth.jsp] not found
        at org.apache.jasper.compiler.DefaultErrorHandler.jspError(DefaultErrorHandler.java:41)
        at org.apache.jasper.compiler.ErrorDispatcher.dispatch(ErrorDispatcher.java:275)
        at org.apache.jasper.compiler.ErrorDispatcher.jspError(ErrorDispatcher.java:91)
        at org.apache.jasper.compiler.Parser.processIncludeDirective(Parser.java:323)
        at org.apache.jasper.compiler.Parser.parseIncludeDirective(Parser.java:358)
        at org.apache.jasper.compiler.Parser.parseDirective(Parser.java:461)
        at org.apache.jasper.compiler.Parser.parseFileDirectives(Parser.java:1782)
        at org.apache.jasper.compiler.Parser.parse(Parser.java:136)
        at org.apache.jasper.compiler.ParserController.doParse(ParserController.java:227)
        at org.apache.jasper.compiler.ParserController.parseDirectives(ParserController.java:117)
        at org.apache.jasper.compiler.Compiler.generateJava(Compiler.java:194)
        at org.apache.jasper.compiler.Compiler.compile(Compiler.java:356)
        at org.apache.jasper.compiler.Compiler.compile(Compiler.java:336)
        at org.apache.jasper.compiler.Compiler.compile(Compiler.java:323)
        at org.apache.jasper.JspCompilationContext.compile(JspCompilationContext.java:570)
        at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:356)
        at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:396)
        at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:340)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:725)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:291)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
```

Make a call to getService.html with no id. Do this directly in the browser, and not in an ajax request

**Comment by darkape** [comment]
lol, I must have copied the same line from the authFailure file since this has the same stupid typo. easy fix
